version: '3'
services:
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - 16379:6379
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=utest
